### ISSUE TITLE
Voice activation color too dark

### ISSUE THREAD

**Issue by skibblesx** [datsfilipe/smooth-theme#2]
When a user speaks the text goes black and makes the name unreadable. 
![qFDrlxv](https://user-images.githubusercontent.com/35665491/144186365-486955b4-0ffe-4fb2-8471-d2b617877be7.png)

**Comment by datsfilipe** [comment]
Thanks for the report, i'll fix it as soon as i can.

**Comment by datsfilipe** [comment]
That should be fixed now, with the new version
