### ISSUE TITLE
DM Video doesn't display in Focus mode

### ISSUE THREAD

**Issue by skibblesx** [datsfilipe/smooth-theme#3]
When in video calls the focus mode shows nothing

![asdfasdf](https://user-images.githubusercontent.com/35665491/144329137-0e76c797-e5f7-4539-b46f-ad2e4330c31e.png)

**Comment by datsfilipe** [comment]
Thanks for the report, i'll fix it as soon as i can.

**Comment by datsfilipe** [comment]
That should be fixed now, with the new version
