### ISSUE TITLE
Windows window control buttons?

### ISSUE THREAD

**Issue by SilverMarcs** [datsfilipe/smooth-theme#4]
Love the theme but could you instruct how to get default window control buttons on windows instead of the macOS buttons? Thanks.

Edit: Could you also tell how to change the entire titlebar bg color? Total noob about all this I should mention

**Comment by datsfilipe** [comment]
This is not editable at the moment, as button import is in the theme source file and not the theme file itself.

I plan to add in a future new version the possibility to decide the titlebar buttons, so the most I can do is ask you to wait until then.

**Comment by datsfilipe** [comment]
That should be fixed now, in the new version i opted to remove the mac style buttons
