### ISSUE TITLE
Region select in DM is not colored

### ISSUE THREAD

**Issue by marknefedov** [datsfilipe/smooth-theme#5]
![image](https://user-images.githubusercontent.com/20001291/145880474-c0995b3a-bd34-43ad-8dc3-0282c3c76c58.png)

**Comment by datsfilipe** [comment]
where? i don't see it

**Comment by marknefedov** [comment]
This is in direct calls in upper right corner.

**Comment by datsfilipe** [comment]
That should be fixed now, with the new version
