### ISSUE TITLE
Minor incompatability with plugin/theme repo

### ISSUE THREAD

**Issue by marknefedov** [datsfilipe/smooth-theme#6]
![image](https://user-images.githubusercontent.com/20001291/145880682-a28bfed5-50ab-441f-9d67-ac195538e0b6.png)
The download button and text are same color.

**Comment by marknefedov** [comment]
This also affects "Screen share" settings
![image](https://user-images.githubusercontent.com/20001291/145960781-9462448c-92bd-4d61-9ad7-be51fab1849f.png)

**Comment by datsfilipe** [comment]
That should be fixed now, with the new version
