### ISSUE TITLE
Window control buttons overlap on macOS (and some general issues)

### ISSUE THREAD

**Issue by SynergyBest** [datsfilipe/smooth-theme#7]
On macOS the buttons to control the window overlap with the discord button
![image](https://user-images.githubusercontent.com/72149158/147420519-98cdff05-8d05-4b14-82eb-9dbe1f2fd01b.png)

**Comment by SynergyBest** [comment]
May I suggest allowing the user to edit the accent color?

**Comment by SynergyBest** [comment]
The center button is also completely rounded while the side buttons are not (look at the bottom right corner)
![image](https://user-images.githubusercontent.com/72149158/147420662-047ec735-b3a4-4962-bbb1-71678224d36c.png)

**Comment by SynergyBest** [comment]
the mute and camera buttons also have no background accent, and the the text on the hangup button is slightly inconsistent because all the other buttons have white text
![image](https://user-images.githubusercontent.com/72149158/147420690-0e6f5144-678c-4d60-9c0c-d31974e522b6.png)

**Comment by datsfilipe** [comment]
> On macOS the buttons to control the window overlap with the discord button ![image](https://user-images.githubusercontent.com/72149158/147420519-98cdff05-8d05-4b14-82eb-9dbe1f2fd01b.png)

macOS uses system titlebars, right? this is weird

**Comment by SynergyBest** [comment]
No they do not

**Comment by SynergyBest** [comment]
ITerm2, a native terminal emulator:
![image](https://user-images.githubusercontent.com/72149158/147421042-7116b622-1914-4114-bdea-7d4c46f321c6.png)
Google Chrome:
![image](https://user-images.githubusercontent.com/72149158/147421068-06bfeba4-505b-4f10-ac16-abd743c5c340.png)
Dash.app (https://kapeli.com/dash):
![image](https://user-images.githubusercontent.com/72149158/147421093-428155e6-5118-4d35-b2eb-64292727e542.png)

These are just examples of applications not using a system title bar

**Comment by SynergyBest** [comment]
macOS system applications however, do have the same titlebar but I'm not sure if they are system titlebars. I've noticed that the majority of electron apps (discord included) seem to have the menu buttons integrated into the main window.
